### ISSUE TITLE
Conflicting

### ISSUE THREAD

**Issue by dynamicsoldier** [LambdAurora/LambdaControls#35] opened 2020-10-31 11:04 UTC
**Describe the bug**
Lambdacontrols conflicts with optifabric and will not open
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Minecraft [e.g. 1.14.4]
 - Fabric [e.g. fabric 0.7.2+build.174]
 - Mods [e.g. aurora_keystrokes v1.0.0, modmenu v1.7.15]
 - Version [e.g. 1.0.0]
 - Branch [e.g. dev]

**Additional context**

**Comment by LambdAurora** [comment] 2020-10-31 11:08
Duplicate of #25.

This will not be fixed as OptiFine changes too much things in the code without letting other modders have enough information to fix.

**Closed as completed by LambdAurora** 2020-10-31 11:08 UTC
Labels: bug, duplicate, wontfix
