### ISSUE TITLE
Right stick movement PS3 controller

### ISSUE THREAD

**Issue by Dragonracer1973** [LambdAurora/LambdaControls#11] opened 2020-01-25 13:42 UTC
**Describe the bug**
First off Love this mod as I initially played minecraft on the PS3. I have a lower end system and after installing the mod (along with others) I notice a sever  bit of input lag for the right anaolog stick. Cursor still works good in game while running the instance, but the controller is laggy.

**Comment by Dragonracer1973** [comment] 2020-01-25 13:48
Oh I am using version 1.0.1 forgot to add that srry

**Comment by LambdAurora** [comment] 2020-02-05 07:09
Hello, does the bug is still there with version 1.10?

**Comment by Dragonracer1973** [comment] 2020-02-05 13:48
I hope to test this soon, I have been a bit busy, I will try within the week.

**Comment by Dragonracer1973** [comment] 2020-02-05 14:58
Updated to version 1.1.0 and the issue does persist.

**Comment by LambdAurora** [comment] 2020-02-05 15:19
Ok, I'll look into it but I need more information.

Is your average frame rate low? (If you can give me a range it would be perfect)

If you can, I would like a video to see the problem. ^^

**Comment by Dragonracer1973** [comment] 2020-02-08 13:33
As I stated previously, my pc is a tater (integrate everything) I have tried making a video of it, but my Minecraft instances are usually capped at around 30 fps. The video turns out like crap, I will include it, but trust me when I say, I have a usual smooth transition with the mouse, and the controller stutters/locks into position

[controller test.zip](https://github.com/LambdAurora/LambdaControls/files/4174261/controller.test.zip)

**Comment by LambdAurora** [comment] 2020-02-08 15:24
So the average FPS is really what I needed so, now I am able to reproduce the problem, which is already noticeable at 60 FPS. In the current state of the code, I'm not sure how I can fix this.

I'll try fix this as soon as possible but that camera control is really hard to implement with Minecraft's spaghetti code.

**Comment by Dragonracer1973** [comment] 2020-02-09 22:38
I understand, thanx for the hel[p, not that I know anything of coding, but you cannot simply map the mouse movement code directly to the right analog stick??

**Comment by LambdAurora** [comment] 2020-02-09 22:45
Well, that was the first version of the code and it was really bad.

The problem is the camera update depends of FPS and I can't inject anywhere the code else it won't work at all. I'm not sure if I can fix it alone.

**Comment by LambdAurora** [comment] 2020-06-27 13:47
Hello, this will be fixed in the next update as I figured out the code to make rotation persistent!

With 30FPS it still feels laggy but it's not really possible to do better.

It will be in the version of the mod for 1.16, if you absolutely want a backport of this feature to 1.15 please tell me.

**Comment by LambdAurora** [comment] 2020-06-27 17:12
Should be fixed in 1.16 (1.3.0) and in 1.15 (1.2.0)!

**Closed by LambdAurora** 2020-06-27 17:12 UTC
Labels: bug
