### ISSUE TITLE
MultiMC, settings of key mapping are not saved, OptiFabric conflict.

### ISSUE THREAD

**Issue by f-c-s** [LambdAurora/LambdaControls#31] opened 2020-09-06 20:56 UTC
Hello,

The settings of key mapping are not saved on exit.
Each time I open Minecraft I have to set key mapping again.

I didn't test it on single installation of MC.

There is a conflict between your mod and OptiFabric mod.

Regards
ML

**Comment by AMereBagatelle** [comment] 2020-09-06 21:14
I believe the conflict between this mod and OptiFabric is intentionally specified.  (unfixable code conflicts)  You can find alternatives for OptiFabric here: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

**Comment by LambdAurora** [comment] 2020-09-07 07:13
> The settings of key mapping are not saved on exit.
Each time I open Minecraft I have to set key mapping again.

This is concerning but despite whatever I do I cannot reproduce this issue, please specify what version of the mod you are using, there is a template for bug reports and it's for a good reason.

> OptiFine

I'm not willing to spend time trying to fix an incompatibility caused by the intrusive nature of a mod which is closed source thus making it very difficult to fix the issue legally.

**Comment by f-c-s** [comment] 2020-09-08 19:34
Hello,

I use MultiMC and I have a few instances of Minecraft, one for 1.12.2 with forge, and 1.15.2 and 1.16.2 with fabric and your mod for gamepad.
The LambdaControl v 1.5.0+1.16.2 is installed for Minecraft 1.16.2, the size of mod is 576027 byes.

Regards
ML

**Comment by Computerlabrat** [comment] 2021-03-01 20:00
It crashes on Minecraft 1.16.5 with optifabric for me. I can't even launch with it. If it helps, I'm using optifabric-1.9.2 and OptiFine_1.16.5_HD_U_G6.

**Comment by DragonEggBedrockBreaking** [comment] 2021-03-01 20:03
> It crashes on Minecraft 1.16.5 with optifabric for me. I can't even launch with it. If it helps, I'm using optifabric-1.9.2 and OptiFine_1.16.5_HD_U_G6.

LambdAurora mentions that she will not fix this and optifine is marked as incompatible in fabric.mod.json. Consider Sodium.

**Comment by Computerlabrat** [comment] 2021-03-01 21:11
I've thought about it. The main problem is that there are some shaders I use that I don't want to give up as there's no precompiled jar file that works with the shaders I use. I use some realistic texture packs.

**Comment by supsm** [comment] 2021-03-01 23:48
Texture packs should work with vanilla, and if you want shaders I recommend checking out [canvas](https://github.com/grondag/canvas). It has some optifine shader features, such as shadows and reflections.

**Comment by Computerlabrat** [comment] 2021-03-02 17:00
It doesn't support the same shaders. I'm not sure if it has ports for ones I like or not. The ones I have are Arcane Shaders, Beyond Belief Legacy, BSL, Chocapic, Nostalgia, SEUS Renewed, and Simplicissimus. I do wonder if it supports connected textures, though.

**Comment by supsm** [comment] 2021-03-02 18:52
[connected block textures](https://github.com/Nuclearfarts/connected-block-textures) is compatible with canvas... also you probably just have to make a trade off with the shaders

**Comment by Computerlabrat** [comment] 2021-03-02 22:56
Tried it, Unless there's a site with Canvas Shaders, my other option might be to suggest the Optifine team to implement controller support.

**Comment by supsm** [comment] 2021-03-02 22:58
https://github.com/spiralhalo/LumiLights/tree/wip

**Comment by LambdAurora** [comment] 2021-06-23 12:20
ButtonBinding not being saved got fixed in e652390.

**Closed as completed by LambdAurora** 2021-06-23 12:20 UTC
Labels: bug
